# Generated by Django 4.1.4 on 2023-03-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="coupon",),
    ]
