# Generated by Django 4.1.4 on 2022-12-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0002_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="product",),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(to="productorder.productoder"),
        ),
    ]
