# Generated by Django 4.1.4 on 2023-03-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0002_remove_order_coupon"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderCoupon",),
    ]
