# Generated by Django 4.1.4 on 2023-03-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0003_delete_ordercoupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("discount", models.IntegerField()),
                ("created", models.DateField(auto_now_add=True)),
                ("expires", models.DateField()),
            ],
        ),
    ]
