# Generated by Django 4.1.4 on 2022-12-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0004_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="paid", field=models.BooleanField(default=False),
        ),
    ]
