# Generated by Django 4.1.4 on 2022-12-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0005_order_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="product", new_name="products",
        ),
    ]
