# Generated by Django 4.1.4 on 2022-12-22 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0006_rename_product_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
