# Generated by Django 4.1.4 on 2022-12-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0008_alter_order_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
