# Generated by Django 4.1.4 on 2023-01-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productorder", "0009_alter_order_reference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="paid", new_name="checked",
        ),
    ]
