# Generated by Django 4.1.4 on 2022-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products")),
                ("name", models.CharField(max_length=40)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=100.0, null=True
                    ),
                ),
            ],
        ),
    ]
