# Generated by Django 4.1.4 on 2023-04-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products")),
                ("name", models.CharField(max_length=40)),
                ("initial_price", models.IntegerField()),
                ("description", models.TextField()),
                ("discount", models.IntegerField(blank=True, null=True)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("categories", models.ManyToManyField(to="products.categories")),
            ],
        ),
    ]
