# Generated by Django 4.1.4 on 2023-04-17 21:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="products"
            ),
        ),
    ]
