# Generated by Django 4.1.4 on 2022-12-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_categories_delete_category_products_categories"),
    ]

    operations = [
        migrations.RemoveField(model_name="products", name="categories",),
        migrations.DeleteModel(name="Categories",),
    ]
