# Generated by Django 4.1.4 on 2022-12-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_categories_products_categories"),
    ]

    operations = [
        migrations.RemoveField(model_name="products", name="categories",),
        migrations.AddField(
            model_name="products",
            name="categories",
            field=models.ManyToManyField(to="products.categories"),
        ),
    ]
