# Generated by Django 4.1.4 on 2023-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rename_price_products_initial_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
