# Generated by Django 4.1.4 on 2023-02-16 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_products_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
